GET http://localhost:3003/api/blogs/

###
POST http://localhost:3003/api/blogs/ HTTP/1.1
content-type: application/json

{
    "title": "test2",
    "author": "test2",
    "url": "test2",
    "likes": 1
}